### ISSUE TITLE
[Bug] Fixed Position Footer

### ISSUE THREAD

**Issue by agusm** [creativetimofficial/ct-argon-dashboard-pro-react#10]
### Version
1.0
### Reproduction link
https://demos.creative-tim.com/argon-dashboard-pro-react/#/documentation/footer
### Operating System
MacOS
### Device
Mac
### Browser & Version
Chrome
### Steps to reproduce
1. create form
2. form just have a few component/input
3. footer follow the last content, not fixed in bottom
### What is expected?
Footer with fixed on bottom position
### What is actually happening?
Admin Footer not fixed in bottom when content (Form) just a few component.

---

**Comment by einazare** [comment]
Hello again, @agusm ,

I believe that we do not have the mentioned functionality.
Could you please share with us a sample of what you are trying to achieve?

Best,
Manu
