### ISSUE TITLE
[Bug] Reference Not Working

### ISSUE THREAD

**Issue by danmight** [creativetimofficial/ct-argon-dashboard-pro-react#11]
### Version
1.0.0
### Reproduction link
https://www.com
### Operating System
Mac OS
### Device
Macbook Pro
### Browser & Version
MacOS
### Steps to reproduce
I just ordered this and had to update a bunch of npm packages which isn't a big deal, but then none of the import or require lines for files are correct. I'm having to manually update all of them with ../../ to get the right import file. I'd prefer to just get a refund. I've only had it for a few hours. The last package I got through you guys was awesome and worked great.
### What is expected?
All the imports would be correct.
### What is actually happening?
I'm having to change them all their relative paths.

---

**Comment by einazare** [comment]
Hello there, @danmight ,

Thank you for your interest in working with our products.
Please read our live docs here: https://demos.creative-tim.com/argon-dashboard-pro-react/#/documentation/quick-start
Also, you can use the jsconfig.json file to make use of absolute imports with the following code inside it:
```
{
  "compilerOptions": {
    "baseUrl": "src",
    "paths": {
      "*": ["src/*"]
    }
  }
}
```

Best,
Manu

**Comment by danmight** [comment]
This fixed it. Thanks! I'd include it with the package in the future.

**Comment by einazare** [comment]
Hello again, @danmight ,

It is included in the download, but for some reason, the .env file on some machines is hidden, and upond the download is ignored.

Best,
Manu
