### ISSUE TITLE
[Bug] SideNav looks strange after making window larger

### ISSUE THREAD

**Issue by mim-ms** [creativetimofficial/ct-argon-dashboard-pro-react#13]
### Version
1.0.0
### Reproduction link
https://demos.creative-tim.com/argon-dashboard-pro-react/#/admin/dashboard
### Operating System
Windows 10, Mac 10.15, Linux Debian 10
### Device
Desktop/Laptop
### Browser & Version
Firefox 70, Chrome 78, Safari 13
### Steps to reproduce
1. Make your browser window less than 1,200 pixel wide
2. Open the link to the dashboard
3. Resize the browser window greater than 1,200 pixels wide
4. Look at the sidenav on the left part of the browser
5. Mouse over the sidenav to make it refresh and fix itself
### What is expected?
The sidenav should look normal, either open or collapsed.
### What is actually happening?
The sidebar is a mix of open and collapsed.  It's open in the sense that it's not the collapsed-style of sidenav.  You can see icons and the first letter of each link.  The rest of the sidenav is being hidden by the main content container.

---
### Additional comments
Argon Dashboard Pro (Bootstrap 4 version, non-React) also has this problem.

**Comment by einazare** [comment]
Hello there, @dmimms ,

Thank you for your interest in working with our products.
At the moment, the only solution that I was able to come up with is this one: https://stackoverflow.com/a/14915697

I will try to figure out a better way of solving this and will add it in our next update.

Best,
Manu

**Comment by Kliton** [comment]
Up
