### ISSUE TITLE
[Feature Request] Bootstrap 4.3.x and other updates found in Argon Dashboard Pro v1.1.1

### ISSUE THREAD

**Issue by mim-ms** [creativetimofficial/ct-argon-dashboard-pro-react#14]
### What is your enhancement?
Please apply the changes to the React version that were applied to the non-React version (Argon Dashboard Pro v1.1.1):

### Boostrap Update, Libraries Update
- Bootstrap updated to `4.3.1`
- libraries updated to latest versions
- fixed _icons.scss calc()

**Comment by einazare** [comment]
Hello there, @dmimms ,

Will see when we'll have some spare time and make a quick update to this product as well.

Best,
Manu
