### ISSUE TITLE
[Bug] Error with node module installation

### ISSUE THREAD

**Issue by omoniyi-remitly** [creativetimofficial/ct-argon-dashboard-pro-react#16]
### Version
1.0.0
### Reproduction link
https://demos.creative-tim.com/argon-dashboard-pro-react/#/admin/dashboard
### Operating System
mac os x
### Device
mac book pro
### Browser & Version
chrome
### Steps to reproduce
npm install
### What is expected?
npm install
### What is actually happening?
npm install

npm WARN deprecated fsevents@1.2.4: Way too old
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the leg
acy v1
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of is
sues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated core-js@2.6.4: core-js@<3 is no longer maintained and not recommended for usage due to the number of iss
ues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actua
l version of core-js@2.
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support
). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgr
ade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <
https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support
). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgr
ade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support
). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgr
ade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! Unexpected end of JSON input while parsing near '...c43U2q1NoKxJ80\ne4L4i'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/omoniyiomotoso/.npm/_logs/2020-02-09T19_04_21_434Z-debug.log

---
### Additional comments
My node version is 9.4.0 and npm version is 5.6.0

**Comment by einazare** [comment]
Hello there, @omoniyi-remitly ,

Please read this thread: https://github.com/creativetimofficial/ct-argon-dashboard-pro-react/issues/6
Also, you might be interested in my last comment: https://github.com/creativetimofficial/ct-argon-dashboard-pro-react/issues/6#issuecomment-566452918

Best,
Manu
