### ISSUE TITLE
Sweet Alert wrong position

### ISSUE THREAD

**Issue by anicache08** [creativetimofficial/ct-argon-dashboard-pro-react#19]
Hi something is wrong with the sweet alert position in your demo website. Please check this screenshot for your reference. Thanks

![image](https://user-images.githubusercontent.com/19280515/78216304-1d3f1a00-74ec-11ea-8391-85b202c47409.png)

**Comment by einazare** [comment]
Hello there, @anicache08 ,

Thank you for your interest in working with our products.
1. Create the following file: `src/assets/scss/react/plugins/_plugin-react-bootstrap-sweetalert.scss`
2. Inside `src/assets/scss/react/react-differences.scss` between lines `6` and `7` add `@import "plugins/plugin-react-bootstrap-sweetalert";`
3. Inside the new created file add the following code:
```
@include media-breakpoint-up(sm) {
  .sweet-alert{
    margin-top: 100px !important;
  }
}
@include media-breakpoint-down(sm) {
  .sweet-alert{
    margin-top: 50px !important;
  }
}

```

Best,
Manu

**Comment by anicache08** [comment]
Yup it works. Thanks @EINazare
