### ISSUE TITLE
How to create form wizard ?

### ISSUE THREAD

**Issue by hung1998pro** [creativetimofficial/ct-argon-dashboard-pro-react#20]
Hi Creative-Tim,
I need to create a wizard form looks like your UI kits like this
![image](https://user-images.githubusercontent.com/22428822/78420626-fe22c280-767a-11ea-96ee-c23ef5b21c25.png)
Or this
![image](https://user-images.githubusercontent.com/22428822/78420634-0aa71b00-767b-11ea-8787-5297350c8dd7.png)
There's no wizard form in argon dashboard theme so how can I achieve this .
Thank in advance.

**Comment by einazare** [comment]
Hello there, @hung1998pro ,

We're sorry, but that component was not created for this product as well.
I'll leave this issue open, and maybe someone will come to your help.
You can use our react-wizard component for that: https://www.npmjs.com/package/react-bootstrap-wizard
But you will have to make your own styles.
Also, this falls into the custom development, might I suggest you speak with our Custom Development team here: [https://services.creative-tim.com/](https://services.creative-tim.com/?ref=github-adpr-issue-20)

Best,
Manu

**Comment by hung1998pro** [comment]
Thank you @EINazare, I've tried your plugin and it's awesome
