### ISSUE TITLE
Request the tab component

### ISSUE THREAD

**Issue by hung1998pro** [creativetimofficial/ct-argon-dashboard-pro-react#22]
How can I create a tab component like this in this theme
![image](https://user-images.githubusercontent.com/22428822/79580240-ede6fa80-80f2-11ea-96bf-649fa62d0450.png)
Because of the default theme UI kits if lack of tab components.

**Comment by einazare** [comment]
Hello again, @hung1998pro ,

We actually have that component implemented in this product as well.
Please take a look here, and let me know if this is what you were looking for: https://demos.creative-tim.com/argon-dashboard-pro-react/#/documentation/navs

Best,
Manu

**Comment by hung1998pro** [comment]
@EINazare Thanks you, but I mean the style :D

**Comment by einazare** [comment]
Hello again, @hung1998pro ,

Unfortunately, the product at hand only comes with these nav components: https://demos.creative-tim.com/argon-dashboard-pro-react/#/documentation/navs
If you want, you can check the following code:
```
import React from 'react';
import { Nav, NavItem, NavLink } from 'reactstrap';

const Example = (props) => {
  return (
    <>
      <Nav>
        <NavItem>
          <NavLink href="#">Link</NavLink>
        </NavItem>
        <NavItem>
          <NavLink href="#">Link</NavLink>
        </NavItem>
        <NavItem>
          <NavLink href="#">Another Link</NavLink>
        </NavItem>
        <NavItem>
          <NavLink disabled href="#">Disabled Link</NavLink>
        </NavItem>
      </Nav>
      <hr />
    </>
  );
}

export default Example;

```

Best,
Manu
