### ISSUE TITLE
How to show existing images in dropzone component

### ISSUE THREAD

**Issue by hung1998pro** [creativetimofficial/ct-argon-dashboard-pro-react#23]
I'm building an edit form for the user to edit the images that they've uploaded but I can not show the Image in your dropzone.
![image](https://user-images.githubusercontent.com/22428822/80066992-35dca600-8567-11ea-89bd-2e33d5bd8e75.png)
According to the official docs of dropzone [displayExistingFiles](https://gitlab.com/meno/dropzone/-/wikis/FAQ#how-to-show-files-already-stored-on-server)
and some solutions on the StackOverflow but still hopeless. I added these code to init function
`
let mockFile = { name: "avatar.jpg", size: 12345 };
                myDropzone.displayExistingFile(mockFile, require('assets/img/samples/avatar.jpg'))
`

--UPDATE--
I've found that when I remove your `previewContainer` and `previewTemplate`, then it works. Here's the picture when I print out the mockFile 
![image](https://user-images.githubusercontent.com/22428822/80076524-860f3480-8576-11ea-8669-688b85676efd.png)
Seems like dropzone can not find the class `dz-preview`, when my dropzone loading the existing images. could you help me find out how to fix this problem

--UPDATE--
I've found the reason why I can not show the existing files because you create preview Template inside the dropzone element
![image](https://user-images.githubusercontent.com/22428822/80084968-cd4ef280-8581-11ea-9008-95910bd459f5.png)
When I move the `dz-preview` element out of `dropzone` div then it works. So, how do I solve this problem

**Comment by einazare** [comment]
Hello there, @hung1998pro ,

We have this covered in our live docs here: https://demos.creative-tim.com/argon-dashboard-pro-react/#/documentation/dropzone

Best,
Manu

**Comment by hung1998pro** [comment]
Hi @EINazare 
Do you really understand my question, I'm looking for how to show the file that I already uploaded in dropzone to edit that upload ...

**Comment by einazare** [comment]
Hello there, @hung1998pro ,

Please make me a video with what are you trying to achieve.

Best,
Manu
