### ISSUE TITLE
[Feature Request] Fixed columns sizes using Bootstrap table

### ISSUE THREAD

**Issue by goliveconsultoria** [creativetimofficial/ct-argon-dashboard-pro-react#27]
### What is your enhancement?
Hi,
I couldn't find a way to render fixed size columns using bootstrap table, avoiding the horizontal scroll bar in the table. I appreciate if you could help me with this.
Thank you.

**Comment by einazare** [comment]
Hello there, @goliveconsultoria ,

At the moment we do not have the component you are asking for.
On our next update, we'll check your enhancement and see if we can integrate it into our product.
If this was intended to be an issue, please fill the accordingly form.

Thank you,
Mnau

**Comment by goliveconsultoria** [comment]
EINazare,
Thanks for the support. I think this will be a really usefull resource for the component.

Also, could you help me with other question, please? I'd like to change the alignment of the columns contents, rendering a button on the center of the column, for example. Is this possible?

Thank you again!

**Comment by einazare** [comment]
Hello again, @goliveconsultoria ,

I am not really sure. 
Can you please tell me what table are you using? 
This product comes with 3 types of tables: react-bootstrap-tables (dynamic), list.js (dynamic), and plain HTML/Bootstrap/Reactstrap tables (static).
And also, if you could share with me an image of what you are trying to achieve, that would help me a lot to understand your use-case and see if there is a solution.

Best,
Manu

**Comment by goliveconsultoria** [comment]
Hey, @EINazare,

I appreciate your answer. I'm using React Bootstrap table, like this:

<ToolkitProvider...
columns={[
...
                    {
                      dataField: "",
                      text: "Actions",
                      formatter: (cell, row) => {
						return(
                                                  `<div>`
						  <a
							className="table-action"
							href="#"
							onClick={(e) => e.preventDefault()}
						  >
							<i className="ni ni-books" />
						  </a>
						  <a
						    className="table-action"
						    href="#"
						    onClick={(e) => e.preventDefault()}
						  >
						    <i className="fas fa-trash" />
						  </a>
						  <a
 						    className="table-action"
						    href="#"
						    onClick={(e) => e.preventDefault()}
						  >
						    <i className="fas fa-user-edit" />
						  </a>
						  <a
						    className="table-action"
						    href="#"
						    onClick={(e) => e.preventDefault()}
						  >
						    <i className="ni ni-check-bold" />
						  </a>
                                                  `</div>`
						);
                      }
                    },
]}
...
>
  {props => (
    <div className="py-4 table-responsive">
       <BootstrapTable...

When the table renders, all the iconesof the column "Actions" are aligned on the left:

![image](https://user-images.githubusercontent.com/66138412/88559143-d4fbb880-d002-11ea-8a13-044286caf364.png)

But I'd like to align the title and the icons on the center of the column, like this:

![image](https://user-images.githubusercontent.com/66138412/88559390-23a95280-d003-11ea-82d0-45e0145cc508.png)


Thank you, again!

**Comment by einazare** [comment]
Hello again, @goliveconsultoria ,

You can add the following css code:
```
.react-bootstrap-table .table th, .react-bootstrap-table .table td {
    text-align: center:
}
```
But this will make all the lines align to the center.

Best,
Manu
