### ISSUE TITLE
Sub Routes...

### ISSUE THREAD

**Issue by ghost** [creativetimofficial/ct-argon-dashboard-pro-react#3]
.

**Comment by einazare** [comment]
Hello there @tmalexandre ,

Thank you for your interest in working with our products.
Can I ask you why haven't you used our issues template? (In the following weeks, we'll add a bot that will auto-close the issues that do not follow our issues template)
```
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US


# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.
```

Also, is this link helpful to you: https://tylermcginnis.com/react-router-nested-routes/

All the best,
Manu
ReactJS Developer at Creative-Tim.com (https://creative-tim.com/)

Trying to help the open source community:

* https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
* https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
* https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f

* https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
* https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx

* https://www.udemy.com/learn-reactjs-with-webpack-4-babel-7-and-material-design/

If you've liked what you saw, help me with a comment, like, share or subscribe.

**Comment by tmalexandre** [comment]
Sorry, I was able to fix my mistake. It was my carelessness. Can you delete this Issue for me?
