### ISSUE TITLE
[Bug] Sidebar nav toggle not working

### ISSUE THREAD

**Issue by mlehmann-sys** [creativetimofficial/ct-argon-dashboard-pro-react#31]
### Version
1.1.0
### Reproduction link
https://demos.creative-tim.com/argon-dashboard-pro-react/#/admin/dashboard
### Operating System
Mac
### Device
Desktop
### Browser & Version
Chrome (all)
### Steps to reproduce
The sidebar toggle in the nav is not shrinking the sidebar.
### What is expected?
Should shrink it
### What is actually happening?
nothing

---

**Comment by einazare** [comment]
Hello there, @mlehmann-sys ,

We've tested the product, and it seems to be working as expected.
Please provide a Step-By-Step guide on how to achieve your issue, if not, please provide a video of the issue.

Best,
Manu

**Comment by mlehmann-sys** [comment]
Video of it happening here:
https://drive.google.com/file/d/12uMNIKAaQ1mRoPbe3PtuJn7U3ixQkxii/view?usp=sharing

Just click the sidebar toggle

**Comment by einazare** [comment]
Hello again, @mlehmann-sys ,

That is a feature of the Sidebar component.
What is happening:
- You click on the Sidebar collapse button buttons
- The Sidebar collapses (goes mini)
- You mouse still hovers over the Sidebar component
- The Sidebar keeps open for you to click on the links

To solve your issue, please, after you have pressed the button, move the cursor away onto the page, you will see that the Sidebar will close.

Best,
Manu

**Comment by mlehmann-sys** [comment]
HAHAHAA Oh my I feel so dumb right now 😆

**Comment by einazare** [comment]
No worries.
