### ISSUE TITLE
[Bug] Sidebar opens when any button is clicked on mobile screen 

### ISSUE THREAD

**Issue by londonbridges13** [creativetimofficial/ct-argon-dashboard-pro-react#33]
### Version
1.1
### Reproduction link
https://demos.creative-tim.com/argon-dashboard-pro-react/?_ga=2.47344686.886913083.1594495019-1365331711.1593482342#/admin/dashboard
### Operating System
MAC OS
### Device
iMAC
### Browser & Version
Chrome
### Steps to reproduce
Step 1: Visit link https://demos.creative-tim.com/argon-dashboard-pro-react/?_ga=2.47344686.886913083.1594495019-1365331711.1593482342#/admin/dashboard

Step 2: Reduce the width to a mobile device

Step 3: Click the new button to the left of filters

The sidebar will open up
### What is expected?
nothing should happen
### What is actually happening?
The sidebar will open up

---
### Solution
idk
### Additional comments
Do you know how to fix if so that the sidebar doesn't open up when clicking a different button?

<img width="1036" alt="Screen Shot 2020-10-24 at 8 09 29 AM" src="https://user-images.githubusercontent.com/11670379/97082945-c6597900-15d2-11eb-9b1c-c9051af8dd5a.png">
<img width="1037" alt="Screen Shot 2020-10-24 at 8 09 43 AM" src="https://user-images.githubusercontent.com/11670379/97082948-c9ed0000-15d2-11eb-841d-1519a1e1e3b5.png">

**Comment by einazare** [comment]
Hello there, @londonbridges13 ,

Thank you for your interest in working with our products.
I've just tested this:

> Step 1: Visit link https://demos.creative-tim.com/argon-dashboard-pro-react/?_ga=2.47344686.886913083.1594495019-1365331711.1593482342#/admin/dashboard
>
>Step 2: Reduce the width to a mobile device
>
>Step 3: Click the new button to the left of filters
>
>The sidebar will open up

And was not able to reproduce your issue. 
Please check it out here: https://imgur.com/ICX9m65
Could you please make a video like the one I did?
Also, maybe the issue comes from one of your extensions, try it in incognito mode as well.

Best,
Manu
