### ISSUE TITLE
[Bug] Unable to run NPM install

### ISSUE THREAD

**Issue by antoniodipinto** [creativetimofficial/ct-argon-dashboard-pro-react#35]
### Version
1.2.0
### Reproduction link
https://stackoverflow.com/questions/66101540/npm-install-unable-to-resolve-dependency-tree
### Operating System
LInux-Windows
### Device
DesktopPC
### Browser & Version
Google Chrome 
### Steps to reproduce
Run in terminal
npm install
### What is expected?
npm installation succesfull
### What is actually happening?
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: argon-dashboard-pro-react@1.2.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.0" from react-bootstrap-table-next@4.0.3
npm ERR! node_modules/react-bootstrap-table-next
npm ERR!   react-bootstrap-table-next@"4.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

---
### Solution
I've tried to downgrade react version in package.json, but still not working. react-bootstrap-table-next still requires a different version of react
### Additional comments
I cannot provide a test link with minimal reproduction. This issue exists here in Romania on my Linux Desktop with Node 15 and also happens on a Windows environment of my colleague

**Comment by einazare** [comment]
Hello there, @antoniodipinto ,

Please install NodeJS LTS version onto your system, that will do the trick.
None of our React products work with the `current` version of NodeJS.

Best,
Manu

**Comment by antoniodipinto** [comment]
Thank you @EINazare, everything worked as expected

**Comment by einazare** [comment]
We'll leave the issue open so that in our next update, we'll add this to our documentation.

**Comment by jhampton** [comment]
I'm using LTS (`default -> lts/* (-> v14.15.1)`), and with the latest NPM `7.21.0` I receive the same error.

The dependency tree for the `Dashboard` products is deep and there are quite a few out-of-date dependencies.  I'm not sure these templates are usable in their current state and age.  Is this something you're working to address?

Thank you!

**Comment by DavidFaermanPendo** [comment]
Thanks @jhampton you prevented that i made the mistake to buy this

**Comment by sajadevo** [comment]
**Hi @jhampton **

Yup we're working on updates for the products and they will be released soon with the latest dependencies used for these products, also for the new version you'll see a free new design and well structured code and components for an easier workflow.

**All the best
Sajad**

**Comment by VolckaertAchiel** [comment]
@sajadevo any update on a eta? i really need this to work....

**Comment by sajadevo** [comment]
@VolckaertAchiel yup by the end of this month the new version of the product will be launched.

**Comment by gelooo20** [comment]
Hi, I've been having similar issues on this matter is there a fix for it? 

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
PS D:\dev\Portfolio\argon> npm install
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: argon-dashboard-pro-react@1.2.1
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.0" from react-bootstrap-table-next@4.0.3
npm ERR! node_modules/react-bootstrap-table-next
npm ERR!   react-bootstrap-table-next@"4.0.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See C:\Users\Angelo\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Angelo\AppData\Local\npm-cache\_logs\2022-07-19T06_33_22_289Z-debug.log



I've already installed the NodeJS 16.16.0 LTS version but it's still having the same issue. How can i resolve this

**Comment by sajadevo** [comment]
**Hi @Oleg1220**

Which version of the product you're using?

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

**Comment by gelooo20** [comment]
Hi Sajad,

I'm sorry for the late reply
I'm currently using the version 1.2.1

[image: image.png]

**Comment by sajadevo** [comment]
Hey @Oleg1220,

I've updated the product to v1.2.2 and this issue is fixed.

Regards,
Sajad
