### ISSUE TITLE
Broken links in Documentation (Typography)

### ISSUE THREAD

**Issue by rmbasilio** [creativetimofficial/ct-argon-dashboard-pro-react#4]
!!! IF YOU DO NOT USE THIS ISSUES TEMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Text Utilities and Color Utilities links found in the typography documentation lead to a useful link. Links found in this page: https://demos.creative-tim.com/argon-dashboard-pro-react/#/documentation/typography

# Current Behavior

Links lead to a 404 error

# Failure Information (for bugs)

TextUtilities leads to: https://demos.creative-tim.com/argon-dashboard-pro-react/argon-dashboard/docs//utilities/text/

ColorUtilities leads to: https://demos.creative-tim.com/argon-dashboard-pro-react/argon-dashboard/docs//utilities/colors/

**Comment by einazare** [comment]
Hello there, @rmbasilio ,

Thank you for your interest in working with our products and for noticing this issue.
Those links should not be there at all.
I've just updated our live doc.
If the changes are not visible right away, then the live docs have been cached on your browser. Refresh a few times, use a different browser or use Incognito Mode / Private Mode on your browser.

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

Trying to help the open source community:

* https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
* https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
* https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f



* https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
* https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx
* https://www.youtube.com/watch?v=BMPHfnAA9iI&list=PLWxSJr7LCl87rxd7A4j9WEFUbJz4gTNLa



* https://www.udemy.com/learn-reactjs-with-webpack-4-babel-7-and-material-design/
* https://www.udemy.com/how-to-use-react-with-firebase-and-redux/


If you've liked what you saw, help me with a comment, like, share or subscribe.
