### ISSUE TITLE
[Bug] Multi level menu not working

### ISSUE THREAD

**Issue by Daniel-Raz-Supersmart** [creativetimofficial/ct-argon-dashboard-pro-react#47]
### Version
 1.2.1
### Reproduction link
https://demos.creative-tim.com/argon-dashboard-pro-react/#/admin/dashboard
### Operating System
Windows 10
### Device
Desktop PC
### Browser & Version
Google Chrome
### Steps to reproduce
1. open demo dashboard
2. navigate to Components on side-nav 
3. click on multi level
### What is expected?
multi-level menu works
### What is actually happening?
not opening

---

**Comment by sajadevo** [comment]
**Hi @Daniel-Raz-Supersmart**
Thanks for using our product, and helping us to make it better, we will take care of that issue on our next update for Argon Dashboard PRO React.

**All the best**
**Sajad**

**Comment by Daniel-Raz-Supersmart** [comment]
Thanks, Where can I see if and when updates have been made?

**Comment by sajadevo** [comment]
**Hi @Daniel-Raz-Supersmart **

We will do a new release on github and it will remind you that a new release is happened.

**All the best
Sajad**

**Comment by Daniel-Raz-Supersmart** [comment]
Great, Thanks!

**Comment by Daniel-Raz-Supersmart** [comment]
> **Hi @Daniel-Raz-Supersmart **
> 
> We will do a new release on github and it will remind you that a new release is happened.
> 
> **All the best Sajad**

Hi, Is there an expected release of the update?

**Comment by sajadevo** [comment]
**Hi there**

As you know its the end of the year and people are in vacation but the release will probably happened on February.

**Comment by Daniel-Raz-Supersmart** [comment]
Hi again, 
February it's late for us, maybe you can point me where the problem is and how can I solve it?

**Comment by krystian-booker** [comment]
Issue still exists @sajadevo

**Comment by ldgonzalez26** [comment]
Do we have an expected date for this issue to be solved ?? its being 4ever

**Comment by ldgonzalez26** [comment]
@krystian-booker @sajadevo The issue is that setState basically replace the entire state of the component.

This would make the trick and if you want it to only work for multilevel just wrap the code with an if 4 example if state === 'multiCollapse' 
setState((prevState) => { 
return { ...prevState, ...st };
});
