### ISSUE TITLE
[Bug] NPM INSTALL issues

### ISSUE THREAD

**Issue by gelooo20** [creativetimofficial/ct-argon-dashboard-pro-react#52]
### Version
1.2.1
### Reproduction link
https://github.com/Oleg1220/Portfolio
### Operating System
Windows 11
### Device
ASUS ROG STRIX G15
### Browser & Version
Chrome 103.0.5060.134
### Steps to reproduce
1. run command NPM INSTALL
### What is expected?
error code like this 

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: argon-dashboard-pro-react@1.2.1
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.0" from react-bootstrap-table-next@4.0.3
npm ERR! node_modules/react-bootstrap-table-next
npm ERR!   react-bootstrap-table-next@"4.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\ernia\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ernia\AppData\Local\npm-cache\_logs\2022-07-21T14_03_35_192Z-debug-0.log
### What is actually happening?
i dont really know i just tried installing the dependencies of the framework

---

**Comment by sajadevo** [comment]
**Hi @Oleg1220**

Thanks for using our product, please run the following command: `npm i  --legacy-peer-deps`

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
