### ISSUE TITLE
[Bug] Installation Issues

### ISSUE THREAD

**Issue by gelooo20** [creativetimofficial/ct-argon-dashboard-pro-react#54]
### Version
v1.2.1
### Reproduction link
https://github.com/Oleg1220/ReactIssues.git
### Operating System
MacOS Monterey Version 12.6
### Device
Macbook Pro(13-inch M2, 2022)
### Browser & Version
Version 105.0.5195.125 (Official Build) (arm64)
### Steps to reproduce
1. yarn Install
2. yarn start
### What is expected?
Open a localhost web app
### What is actually happening?
Failed to compile

Node sass are depracated

---

**Comment by sajadevo** [comment]
Hi @Oleg1220,

node-sass issue is already fixed you just need to update to the latest version of the product (v1.2.3).

Regards,
Sajad
