### ISSUE TITLE
[Bug] react version issues

### ISSUE THREAD

**Issue by dragonslair** [creativetimofficial/ct-argon-dashboard-pro-react#56]
### Version
1.2.4
### Reproduction link
https://www.noaddress.com
### Operating System
Windows 11
### Device
X1 Thinkpad
### Browser & Version
Chrome 119.0.6045.106 
### Steps to reproduce
1. Download files 
2. npm install
### What is expected?
I expect node_modules to be installed without errors
### What is actually happening?
Hi,
I am currently running react 18.2.0.
When i do npm-install i get error: peer react@"^16.3.0" from react-bootstrap-table-next@4.0.3.

I change react version and react-dom in package.json to:
"react": "16.3.0",
"react-dom": "16.3.0",

But then I get error:
peer react@"17.x.x" from react-notification-alert@0.0.13

Please advice on how I can resolve this.

---

**Comment by maisamaf** [comment]
Hey @dragonslair, could you please try the installation by using the command `npm install --legacy-peer-deps`? This should help with any compatibility issues.

Regards,

**Comment by sajadevo** [comment]
This issue is fixed on v1.2.5.
