### ISSUE TITLE
[Bug] unable to resolve dependency tree during the initial npm install

### ISSUE THREAD

**Issue by VictorHenriquez** [creativetimofficial/ct-argon-dashboard-pro-react#58]
### Version
V1.0.0 and node 18.18.2
### Reproduction link
https://github.com/VictorHenriquez/argon-dashboard-pro-react-nodejs-v1.0.0.git
### Operating System
Windows 11
### Device
Laptop Asus VivoBook
### Browser & Version
na
### Steps to reproduce
1. Donwload the project directly by your page.
2. Unzzip the project
3. Open the project in to visual code, open the terminal and go to the backend folder.
4. Run npm install
### What is expected?
install all the node libraries listed in the original pro project.
### What is actually happening?
 npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: nodejs-mongodb-rest-api-login@0.1.0
npm ERR! Found: mongoose@5.13.21
npm ERR! node_modules/mongoose
npm ERR!   mongoose@"^5.9.9" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer mongoose@"^4.9.0" from mongoose-unique-validator@1.0.6
npm ERR! node_modules/mongoose-unique-validator
npm ERR!   mongoose-unique-validator@"^1.0.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\vhenriquez\AppData\Local\npm-cache\_logs\2023-11-29T18_11_50_193Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\vhenriquez\AppData\Local\npm-cache\_logs\2023-11-29T18_11_50_193Z-debug-0.log

---

**Comment by maisamaf** [comment]
Hey @VictorHenriquez, could you please try installing using the command `npm install --legacy-peer-deps`? This should help with any compatibility issues.

Regards,

**Comment by sajadevo** [comment]
This issue is fixed on v1.2.5.
