### ISSUE TITLE
[Bug] NODE_GYP compilation issue

### ISSUE THREAD

**Issue by cyberwombat** [creativetimofficial/ct-argon-dashboard-pro-react#6]
### Version
1.0,0
### Reproduction link
n/a - CLI issue
### Operating System
MacOS Catalina Beta
### Device
2010 Macbook Air
### Browser & Version
n/a
### Steps to reproduce
Unzip downloaded file
run yarn (node version 12.6.0)
Wait for node_gyp errors.
### What is expected?
Install all packages
### What is actually happening?
Compilation error

---
### Solution
I have brought the bundle and am able to run yarn in some other ones. Here are my files
argon-dashboard-pro-react-v1.0.0           material-dashboard-pro-react-v1.7.0
black-dashboard-pro-react-v1.0.0           now-ui-dashboard-pro-react-v1.3.0
light-bootstrap-dashboard-pro-react-v1.2.0 paper-dashboard-pro-react-v1.1.0

It fails in black-dashboard-pro-react-v1.0.0 as well but works in others.

**Comment by einazare** [comment]
Hello there, @cyberwombat ,

Thank you for your interest in working with our products.
Sorry for this late reply. I've been on a small vacation thanks to the Assumption SOLEMNITY celebration of the Catholic and Orthodox faiths (http://www.romcal.net/output/2019.htm).
Our products are not made to work with yarn, this is covered in our live docs on each product.
Please use `npm install` or `npm run install:clean`.

Best,
Manu

**Comment by cyberwombat** [comment]
Ok I used npm. Same exact error.

**Comment by cyberwombat** [comment]
npm log: https://gist.github.com/cyberwombat/6055827dd2c4fb573cf01444663ade9e

**Comment by einazare** [comment]
Hello again, @cyberwombat ,

Can you make a video with the following:
- Login into your account on creative-tim
- Go to the downloads page
- Download the product
- Unzip the product
- Open terminal
- Navigate to the unzipped product
- Run in terminal `npm install`
- Run in terminal `npm start`

If I follow the steps from above, no error shows.
Will wait for the mentioned video.

Best,
Manu

**Comment by cyberwombat** [comment]
Did you try w node 12.6.0? - am on MacOS catalina

**Comment by einazare** [comment]
Hello again, @cyberwombat ,

I did not try node v12.6.0.
I tried on node v12.9.0 and node v10.16.3.
On node v10.16.3 everything works fine, on node v12.9.0 indeed it trows some errors and the product won't start.
It is bad user experience, I give you that, but I do not know what to tell you other than use node v10.16.3 (the LTS version), since the LTS version will always work better than the current one. The current one from my knowledge usually is a testing one.
We will add in our live docs that our product work with nodejs LTS version only.
If you test any of our react product the same issue might occur.

Best,
Manu

**Comment by cyberwombat** [comment]
Ok - all  the other packages except black in the dashboard bundle work fine w 12.6 btw.

**Comment by einazare** [comment]
Hello again, @cyberwombat ,

Will see if I can find a solution.
Please leave the issue open until then.
If I won't be able to find a solution, I will add something inside our live docs that the product only works with node lts.

Best,
Manu

**Comment by artuova** [comment]
The fix is to change the version of react-scripts in package.json to 3.3.0

**Comment by einazare** [comment]
Hello there guys,

To fix the issue you can run:
```
npm i -E node-sass@4.13.0
npm install
npm start
```
Also, on one of our products, one of our users gave us this: https://github.com/creativetimofficial/ct-paper-kit-pro-react/issues/2#issuecomment-565728755

Best,
Manu
