### ISSUE TITLE
Set Fixed Footer

### ISSUE THREAD

**Issue by agusm** [creativetimofficial/ct-argon-dashboard-pro-react#9]
How to Set Footer as Fixed Position?

**Comment by einazare** [comment]
Hello there, @agusm ,

Thank you for your interest in working with our products.
I believe that we do not have the mentioned functionality.
Could you please share with us a sample of what you are trying to achieve?

Also, please next time use our issue template:
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/argon-dashboard-pro-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```

Best,
Manu
